FM-363: Block sync test (#459)
* FM-363: Combine stop and rm into destroy

* FM-363: Try to connect a full node to the existing one

* FM-363: Test that the full node is syncing

* FM-363: Fix init script

diff --git a/fendermint/testing/snapshot-test/Makefile.toml b/fendermint/testing/snapshot-test/Makefile.toml
--- a/fendermint/testing/snapshot-test/Makefile.toml
+++ b/fendermint/testing/snapshot-test/Makefile.toml
@@ -12,12 +12,12 @@ extend = [
 ]
 
 env_files = [
-  { path = "./snapshot.env" },
+  { path = "./scripts/snapshot.env" },
   { path = "../Makefile/common.env" },
   { path = "../Makefile/ci.env", profile = "ci" },
 ]
 
-# Overriding th env file to enable snapshotting.
+# Overriding the env file to enable snapshotting.
 [tasks.test-data-env]
 script = """
 cat << EOF > ${TEST_DATA_DIR}/.env
@@ -32,9 +32,9 @@ EOF
 
 [tasks.test]
 clear = true
-dependencies = ["snapshot-wait", "snapshot-created"]
+dependencies = ["snapshot-wait", "snapshot-created", "fullnode-sync"]
 
-# Wait enought time that some snapshots should be exported.
+# Wait enough time that some snapshots should be exported.
 [tasks.snapshot-wait]
 extend = "wait"
 env = { "CARGO_MAKE_WAIT_MILLISECONDS" = "15000" }
@@ -48,3 +48,68 @@ if [ -z "$(ls -A $FM_SNAPSOTS_DIR)" ]; then
    exit 1
 fi
 """
+
+
+# Set up a full node that syncs with the default one, then stop it.
+[tasks.fullnode-sync]
+run_task = { name = [
+  "fullnode-setup",
+  "fullnode-test",
+], fork = true, cleanup_task = "fullnode-teardown" }
+
+
+[tasks.fullnode-setup]
+dependencies = ["cometbft-export-node-id"]
+env_files = [{ path = "./scripts/fullnode.env" }]
+run_task = { name = [
+  "test-node-dir",
+  "cometbft-init",
+  "fullnode-set-seed",
+  "fullnode-copy-genesis",
+  "fendermint-start",
+  "cometbft-start",
+  "cometbft-wait",
+  "fendermint-logs",
+  "cometbft-logs",
+] }
+
+
+# Set the persistent peer address to that of the default node-0.
+[tasks.fullnode-set-seed]
+env_files = [{ path = "./scripts/fullnode.env" }]
+script = """
+CMT_SEED_ID=$(cat $BASE_DIR/$SEED_NODE_NAME/node-id)
+CMT_PERSISTENT_PEERS=$CMT_SEED_ID@$SEED_CMT_CONTAINER_NAME:26656
+sed -i'' -e "s|persistent_peers = \\"\\"|persistent_peers = \\"$CMT_PERSISTENT_PEERS\\"|" $BASE_DIR/${NODE_NAME}/cometbft/config/config.toml
+"""
+
+
+# Get the genesis from node-0
+[tasks.fullnode-copy-genesis]
+env_files = [{ path = "./scripts/fullnode.env" }]
+script = """
+cp $BASE_DIR/${SEED_NODE_NAME}/cometbft/config/genesis.json \
+   $BASE_DIR/${NODE_NAME}/cometbft/config/genesis.json
+"""
+
+# See if it managed to sync.
+[tasks.fullnode-test]
+env_files = [{ path = "./scripts/fullnode.env" }]
+script = """
+EARLIEST=$(curl -s localhost:${CMT_RPC_HOST_PORT}/status | jq -r ".result.sync_info.earliest_block_height")
+LATEST=$(curl -s localhost:${CMT_RPC_HOST_PORT}/status | jq -r ".result.sync_info.latest_block_height")
+
+if [ "$EARLIEST" = "$LATEST" ]; then
+  echo "ERROR: The chain is not syncing!"
+  exit 1
+fi
+"""
+
+
+[tasks.fullnode-teardown]
+env_files = [{ path = "./scripts/fullnode.env" }]
+run_task = { name = [
+  "cometbft-destroy",
+  "fendermint-destroy",
+  "test-node-dir-rm",
+] }
