Seem to work

diff --git a/fendermint/testing/graph-test/Makefile.toml b/fendermint/testing/graph-test/Makefile.toml
--- a/fendermint/testing/graph-test/Makefile.toml
+++ b/fendermint/testing/graph-test/Makefile.toml
@@ -21,6 +21,7 @@ clear = true
 run_task = { name = [
   "greeter-example",
   "graph-setup",
+  "graph-test",
 ], fork = true, cleanup_task = "graph-teardown" }
 
 
@@ -37,17 +38,56 @@ cargo run -p fendermint_eth_api --release --example greeter -- \
 
 [tasks.graph-setup]
 script = """
-echo "TODO: configure the graph"
+set -x
+echo "Start configuring subgraph..."
+echo "Found deployed contract:"
 cat ${TEST_DATA_DIR}/greeter.json
-echo "TODO: docker-compose up the graph"
+echo "\n"
+
+cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/fendermint
+cp -r testing/graph-test/subgraph testing/graph-test/test-data
+cp testing/graph-test/test-data/greeter.json testing/graph-test/test-data/subgraph/config/testnet.json
+cp testing/contracts/Greeter.abi testing/graph-test/test-data/subgraph/abis/IGreeter.json
+cd testing/graph-test/test-data/subgraph
+npm install
+npm run compile
+npm run graph-node
+
+echo "Waiting for Graph node to start..."
+# Notice that subgraph node does takes a while to spin up
+sleep 30s
+
+npm run create-local
+npm run deploy-local
+
+echo "Subgraph is running now."
 """
 
 [tasks.graph-test]
 script = """
-echo "TODO: run GraphQuery with curl"
+echo "Query against local subgraph server using GraphQL."
+GREETING_MSG_0=$(curl -s 'http://localhost:8000/subgraphs/name/Greeter' --data-raw '{"query":"{\\n  greetings(sort: \\"createdAt:desc\\") {\\n    id\\n    currentGreeting\\n  }\\n}","variables":null,"extensions":{"headers":null}}' | jq -r '.data.greetings[0].currentGreeting')
+GREETING_MSG_1=$(curl -s 'http://localhost:8000/subgraphs/name/Greeter' --data-raw '{"query":"{\\n  greetings(sort: \\"createdAt:desc\\") {\\n    id\\n    currentGreeting\\n  }\\n}","variables":null,"extensions":{"headers":null}}' | jq -r '.data.greetings[1].currentGreeting')
+echo $GREETING_MSG_0
+echo $GREETING_MSG_1
+
+if [ "$GREETING_MSG_0" != "Welcome, weary traveller!" ]; then
+  echo "ERROR: Getting wrong indexed greeting message $GREETING_MSG_1"
+  exit 1
+fi
+
+if [ "$GREETING_MSG_1" != "Howdy doody!" ]; then
+  echo "ERROR: Getting wrong indexed greeting message $GREETING_MSG_0"
+  exit 1
+fi
+
+echo "GraphQL query test PASS."
 """
 
 [tasks.graph-teardown]
 script = """
-echo "TODO: docker-compose down the graph"
+set -x
+cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/fendermint/testing/graph-test/subgraph/graph-node
+echo "Tearing down subgraph..."
+docker-compose down -v
 """
