ENG-719: Tag and push the fendermint builder image

diff --git a/.github/workflows/fendermint-publish.yaml b/.github/workflows/fendermint-publish.yaml
--- a/.github/workflows/fendermint-publish.yaml
+++ b/.github/workflows/fendermint-publish.yaml
@@ -66,6 +66,7 @@ jobs:
         id: prep
         run: |
           IMAGE_ID=ghcr.io/${{ github.repository_owner }}/fendermint
+          IMAGE_BUILDER_ID=ghcr.io/${{ github.repository_owner }}/fendermint-builder
 
           # This changes all uppercase characters to lowercase.
           IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
@@ -80,10 +81,11 @@ jobs:
           [ "$VERSION" == "main" ] && VERSION=latest
 
           echo "IMAGE_TAG=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
+          echo "IMAGE_BUILDER_TAG=$IMAGE_BUILDER_ID:$VERSION" >> $GITHUB_OUTPUT
 
-      # Pull the latest docker image. Its layers might be reused during the build.
+      # Pull the latest docker builder image. Its layers might be reused during the build.
       - name: Docker Pull
-        run: docker pull ghcr.io/consensus-shipyard/fendermint:latest
+        run: docker pull ghcr.io/${{ github.repository_owner }}/fendermint-builder:latest  || echo "builder image not found"
 
       - name: Docker Deps
         run: |
@@ -104,6 +106,7 @@ jobs:
       - name: Build and Push Multiarch Docker Image
         run: |
           export BUILDX_TAG=${{ steps.prep.outputs.IMAGE_TAG }}
+          export BUILDX_BUILDER_TAG=${{ steps.prep.outputs.IMAGE_BUILDER_TAG }}
           export BUILDX_STORE="--push"
           export BUILDX_FLAGS="--platform linux/amd64,linux/arm64 ${BUILDX_FLAGS}"
           cd fendermint && make docker-build
diff --git a/.github/workflows/fendermint-test.yaml b/.github/workflows/fendermint-test.yaml
--- a/.github/workflows/fendermint-test.yaml
+++ b/.github/workflows/fendermint-test.yaml
@@ -90,9 +90,13 @@ jobs:
           path: ./contracts/out
           key: contracts-abi-${{ hashFiles('./contracts/src/**/*.sol') }}
 
-      # Pull the latest docker image. Its layers might be reused during the build.
+      - name: Docker Login
+        shell: bash
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
+
+      # Pull the latest docker builder image. Its layers might be reused during the build.
       - name: Docker Pull
-        run: docker pull ghcr.io/consensus-shipyard/fendermint:latest
+        run: docker pull ghcr.io/${{ github.repository_owner }}/fendermint-builder:latest || echo "builder image not found"
 
       - name: ${{ matrix.make.name }}
         run: cd fendermint && make ${{ matrix.make.task }}
